"""Change is_cover to Boolean

Revision ID: c90ea6244162
Revises: a8e8a464ea0b
Create Date: 2025-05-11 10:46:34.300345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c90ea6244162'
down_revision: Union[str, None] = 'a8e8a464ea0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotel_photos', 'is_cover',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotel_photos', 'is_cover',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
